drones:
  - cf_number: 1
    enabled: true
    offset: [0.0, 1.0, 0.0]
  - cf_number: 2
    enabled: true
    offset: [0.5, 0.5, 0.0]
  - cf_number: 3
    enabled: true
    offset: [0.0, 0.5, 0.0]
  - cf_number: 4
    enabled: true
    offset: [-0.5, 0.5, 0.0]
  - cf_number: 5
    enabled: true
    offset: [0.5, 0.0, 0.0]
  - cf_number: 6
    enabled: true
    offset: [-0.5, 0.0, 0.0]
  - cf_number: 7
    enabled: true
    offset: [0.5, -0.5, 0.0]
  - cf_number: 8
    enabled: true
    offset: [0.0, -0.5, 0.0]  
  - cf_number: 9
    enabled: true
    offset: [-0.5, -0.5, 0.0]
  - cf_number: 10
    enabled: true
    offset: [-1.0, 0.0, 0.0]
